version: "3"

services:
  mongo-micro:
    container_name: mongo-micro
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  redis-micro:
    container_name: redis-micro
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis-data:/var/lib/redis